# Generated by Django 6.0.2 on 2026-02-11 09:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField(help_text='Duration in years')),
                ('course_type', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('DIP', 'Diploma'), ('CERT', 'Certificate')], max_length=10)),
                ('total_seats', models.IntegerField(default=60)),
                ('filled_seats', models.IntegerField(default=0)),
                ('min_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('eligibility_criteria', models.TextField()),
                ('fee_per_year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('previous_school', models.CharField(max_length=200)),
                ('previous_qualification', models.CharField(max_length=100)),
                ('percentage_obtained', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('year_of_passing', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('REQUIRES_DOCUMENTS', 'Requires Additional Documents'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('APPROVED', 'Approved'), ('WAITLISTED', 'Waitlisted')], default='DRAFT', max_length=20)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_eligible', models.BooleanField(default=False)),
                ('eligibility_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmation_deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocation', to='admissions.application')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='admissions.course')),
            ],
            options={
                'ordering': ['-allocation_date'],
            },
        ),
    ]
